FROM python:3.10
ENV PYTHONUNBUFFERED 1 
COPY requirements.txt .
WORKDIR /app 
COPY . /app/
RUN pip install -r requirements.txt
EXPOSE 8000 
CMD ["uvicorn", "--host", "0.0.0.0", "--port", "8000", "src.app.api:app"]
