stages:
  data-processing:
    cmd: python3 src/data/make_dataset.py
    deps:
    - data/raw/Reviews.csv
    - src/data/make_dataset.py
    outs:
    - data/processed/test.csv
    - data/processed/train.csv
