[tool.coverage.run]
omit = ["src/data/*",'src/features/*',"src/visualization/*","src/models/model.py","src/__init__.py","src/models/__init__.py",
"src/models/evaluate_model.py"]


[tool.pytest.ini_options]
testpaths = "tests"
addopts = "--junitxml=out/tests-report.xml"