name: Run tests CI
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Use python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies 
      run: pip install -r requirements.txt

    - name: show cwd
      run : python -c "import os; print('\n',os.getcwd())"

    - name : pull data from dvc
      run : python -m dvc pull -r origin

    - name: Run tests
      run: python -m pytest